import { Ticket, MaintenanceItem, PriorityType, StatusType, OperationalBase, UrgencyConfig } from './types';

export const INITIAL_BASES: OperationalBase[] = [
  { id: 'b1', name: 'Filial São Paulo (Matriz)', active: true, establishment: 'EST-101' },
  { id: 'b2', name: 'Base Paulínia - SP', active: true, establishment: 'EST-102' },
  { id: 'b3', name: 'Base Cubatão - SP', active: true, establishment: 'EST-103' },
  { id: 'b4', name: 'Base Duque de Caxias - RJ', active: true, establishment: 'EST-104' },
  { id: 'b5', name: 'Base Araucária - PR', active: true, establishment: 'EST-105' }
];

export const INITIAL_URGENCY_CONFIGS: UrgencyConfig[] = [
  { id: 'u1', priority: 'Baixa', defaultSlaDays: 5, active: true },
  { id: 'u2', priority: 'Média', defaultSlaDays: 3, active: true },
  { id: 'u3', priority: 'Alta', defaultSlaDays: 2, active: true },
  { id: 'u4', priority: 'Crítica', defaultSlaDays: 1, active: true }
];

export const MAINTENANCE_ITEMS: MaintenanceItem[] = [
  {
    id: '1',
    name: 'Ar Condicionado & Refrigeração',
    category: 'Climatização',
    defaultSlaDays: 2,
    descriptionPlaceholder: 'Ex: Aparelho split do bloco B sala 302 não está gelando ou apresenta vazamento de água.',
    iconName: 'Wind',
    active: true,
    subitems: [
      'Ar-condicionado não resfria',
      'Vazamento de água / Gotejamento',
      'Barulho excessivo na evaporadora/condensadora',
      'Mal cheiro ao ligar o aparelho',
      'Controle remoto quebrado ou sem bateria'
    ]
  },
  {
    id: '2',
    name: 'Elétrica & Iluminação',
    category: 'Elétrica',
    defaultSlaDays: 1,
    descriptionPlaceholder: 'Ex: Queda de disjuntor, tomadas sem energia ou lâmpadas piscando no setor administrativo.',
    iconName: 'Zap',
    active: true,
    subitems: [
      'Lâmpadas apagadas ou piscando',
      'Tomada sem energia ou com mau contato',
      'Queda frequente de disjuntor',
      'Fiação exposta ou curto-circuito',
      'Instalação de novos pontos elétricos'
    ]
  },
  {
    id: '3',
    name: 'Hidráulica & Saneamento',
    category: 'Hidráulica',
    defaultSlaDays: 1,
    descriptionPlaceholder: 'Ex: Torneira vazando, entupimento nos banheiros sociais do 1º andar ou infiltrações.',
    iconName: 'Droplet',
    active: true,
    subitems: [
      'Vazamento em torneira/registro',
      'Vaso sanitário entupido ou vazando',
      'Infiltração ou umidade na parede',
      'Falta de abastecimento de água',
      'Pia ou ralo entupido'
    ]
  },
  {
    id: '4',
    name: 'Manutenção Civil & Pintura',
    category: 'Civil & Infraestrutura',
    defaultSlaDays: 5,
    descriptionPlaceholder: 'Ex: Ajuste de portas, trincas nas paredes, fechadura com defeito ou goteira no teto.',
    iconName: 'Hammer',
    active: true,
    subitems: [
      'Ajuste/Manutenção de portas ou janelas',
      'Fechadura ou maçaneta quebrada',
      'Trincas ou rachaduras na parede',
      'Goteira ou infiltração no telhado',
      'Pintura ou retoque de parede/teto'
    ]
  },
  {
    id: '5',
    name: 'Elevadores & Transporte Vertical',
    category: 'Sistemas',
    defaultSlaDays: 1,
    descriptionPlaceholder: 'Ex: Elevador de carga parou com falha de energia ou emite ruído atípico durante subida.',
    iconName: 'ArrowUpDown',
    active: true,
    subitems: [
      'Elevador travado ou inoperante',
      'Ruído estranho durante deslocamento',
      'Portas com dificuldade de fechamento',
      'Painel de botões quebrado'
    ]
  },
  {
    id: '6',
    name: 'Controle de Acesso & CFTV',
    category: 'Segurança',
    defaultSlaDays: 2,
    descriptionPlaceholder: 'Ex: Catraca eletrônica da recepção não lê cartões ou câmera do estacionamento apagada.',
    iconName: 'ShieldAlert',
    active: true,
    subitems: [
      'Câmera de segurança offline/chuvisco',
      'Catraca ou portão eletrônico travado',
      'Leitor biométrico/tag sem leitura',
      'Alarme disparando sem motivo'
    ]
  },
  {
    id: '7',
    name: 'Limpeza Crítica & Conservação',
    category: 'Limpeza & Conservação',
    defaultSlaDays: 1,
    descriptionPlaceholder: 'Ex: Derramamento de óleo no galpão ou necessidade de higienização de emergência em auditório.',
    iconName: 'Trash2',
    active: true,
    subitems: [
      'Derramamento de resíduos/óleo',
      'Necessidade de limpeza pós-obra',
      'Falta de insumos nos banheiros',
      'Sujeira acumulada em área comum'
    ]
  }
];

export const TECHNICIANS = [
  'Carlos Eduardo (Eletricista Sênior)',
  'Marcos Vinícius (Técnico HVAC)',
  'Julio Cezar (Encanador/Hidráulica)',
  'Roberto Silva (Marceneiro/Civil)',
  'Anderson Melo (Sistemas de Segurança)',
  'Equipe de Facilities Externa (Terceirizada)'
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'CHA-2026-001',
    requesterName: 'Ana Cláudia Reis',
    requesterEmail: 'ana.reis@risel.com.br',
    requesterPhone: '(11) 98765-4321',
    category: 'Climatização',
    subitem: 'Ar-condicionado não resfria',
    operationalBase: 'Filial São Paulo (Matriz)',
    location: 'Bloco A - Diretoria',
    description: 'Ar condicionado principal da sala de reunião presidencial não gela e está fazendo um barulho metálico muito alto.',
    priority: 'Alta',
    status: 'Concluído',
    createdAt: '2026-01-10T08:30:00Z',
    updatedAt: '2026-01-10T12:15:00Z',
    slaDays: 2,
    slaTargetDate: '2026-01-10T12:30:00Z',
    cost: 450.00,
    assignedTechnician: 'Marcos Vinícius (Técnico HVAC)',
    adminNotes: 'Substituição do capacitor de partida da condensadora externa e limpeza do filtro de ar.',
    satisfactionRating: 5,
    feedbackText: 'Atendimento extremamente rápido e preciso. Excelente trabalho!',
    isSlaViolated: false
  },
  {
    id: 'CHA-2026-002',
    requesterName: 'Bruno Alencar',
    requesterEmail: 'bruno.alencar@risel.com.br',
    requesterPhone: '(11) 97654-3210',
    category: 'Elétrica',
    subitem: 'Lâmpadas apagadas ou piscando',
    operationalBase: 'Base Paulínia - SP',
    location: 'Galpão 3 - Linha de Envase',
    description: 'Conjunto de 4 luminárias industriais de LED apagadas na seção de rotulagem, reduzindo a visibilidade da equipe de operação.',
    priority: 'Crítica',
    status: 'Concluído',
    createdAt: '2026-02-15T14:10:00Z',
    updatedAt: '2026-02-15T15:45:00Z',
    slaDays: 1,
    slaTargetDate: '2026-02-15T16:10:00Z',
    cost: 180.00,
    assignedTechnician: 'Carlos Eduardo (Eletricista Sênior)',
    adminNotes: 'Identificado disjuntor desarmado devido a sobrecarga. Trocado o disjuntor defeituoso de 20A por um novo.',
    satisfactionRating: 4,
    feedbackText: 'Atendimento ágil, evitou que a produção ficasse parada por muito tempo.',
    isSlaViolated: false
  },
  {
    id: 'CHA-2026-003',
    requesterName: 'Carla Souza',
    requesterEmail: 'carla.souza@risel.com.br',
    requesterPhone: '(11) 96543-2109',
    category: 'Hidráulica',
    subitem: 'Vazamento em torneira/registro',
    operationalBase: 'Base Cubatão - SP',
    location: 'Refeitório Central - Cozinha',
    description: 'Vazamento volumoso embaixo da pia de preparação industrial, inundando parte do piso do refeitório.',
    priority: 'Alta',
    status: 'Concluído',
    createdAt: '2026-02-28T09:00:00Z',
    updatedAt: '2026-02-28T11:30:00Z',
    slaDays: 1,
    slaTargetDate: '2026-02-28T12:00:00Z',
    cost: 320.00,
    assignedTechnician: 'Julio Cezar (Encanador/Hidráulica)',
    adminNotes: 'Troca de sifão danificado e vedação da conexão com fita veda-rosca líquida.',
    satisfactionRating: 5,
    feedbackText: 'Técnico muito educado e resolveu o vazamento rapidamente.',
    isSlaViolated: false
  },
  {
    id: 'CHA-2026-004',
    requesterName: 'Daniel Oliveira',
    requesterEmail: 'daniel.oliveira@risel.com.br',
    requesterPhone: '(11) 95432-1098',
    category: 'Civil & Infraestrutura',
    subitem: 'Ajuste/Manutenção de portas ou janelas',
    operationalBase: 'Base Duque de Caxias - RJ',
    location: 'Bloco C - Recepção Principal',
    description: 'Fechadura eletromagnética da porta dupla de vidro emperrada, dificultando a abertura completa.',
    priority: 'Média',
    status: 'Concluído',
    createdAt: '2026-03-05T10:00:00Z',
    updatedAt: '2026-03-06T15:00:00Z',
    slaDays: 5,
    slaTargetDate: '2026-03-06T10:00:00Z',
    cost: 580.00,
    assignedTechnician: 'Roberto Silva (Marceneiro/Civil)',
    adminNotes: 'Porta de vidro desregulada raspando no piso, impedindo a trava eletromagnética de fechar. Feita a regulagem das dobradiças pivotantes.',
    satisfactionRating: 3,
    feedbackText: 'Demorou um pouco para concluir (passou de 24h por causa do ajuste complexo do vidro), mas ficou bom.',
    isSlaViolated: true
  },
  {
    id: 'CHA-2026-005',
    requesterName: 'Eduardo Martins',
    requesterEmail: 'eduardo.martins@risel.com.br',
    requesterPhone: '(11) 94321-0987',
    category: 'Sistemas',
    subitem: 'Elevador travado ou inoperante',
    operationalBase: 'Filial São Paulo (Matriz)',
    location: 'Prédio Administrativo - Elevador Social 1',
    description: 'Elevador parado no 4º andar emitindo sinal sonoro de erro intermitente e as portas não abrem.',
    priority: 'Crítica',
    status: 'Concluído',
    createdAt: '2026-03-12T15:30:00Z',
    updatedAt: '2026-03-12T16:15:00Z',
    slaDays: 1,
    slaTargetDate: '2026-03-12T16:30:00Z',
    cost: 950.00,
    assignedTechnician: 'Equipe de Facilities Externa (Terceirizada)',
    adminNotes: 'Acionado suporte emergencial da fabricante Otis. Feito o reset lógico da placa eletrônica do elevador.',
    satisfactionRating: 5,
    feedbackText: 'O socorro chegou em 15 minutos e resolveu o travamento. Nota 10!',
    isSlaViolated: false
  },
  {
    id: 'CHA-2026-006',
    requesterName: 'Fernanda Lima',
    requesterEmail: 'fernanda.lima@risel.com.br',
    requesterPhone: '(11) 93210-9876',
    category: 'Segurança',
    subitem: 'Câmera de segurança offline/chuvisco',
    operationalBase: 'Base Araucária - PR',
    location: 'Estacionamento - Portão 2',
    description: 'Câmera dome de segurança CFTV sem imagem na guarita de monitoramento de saída de caminhões de combustível.',
    priority: 'Alta',
    status: 'Concluído',
    createdAt: '2026-04-02T11:00:00Z',
    updatedAt: '2026-04-02T13:45:00Z',
    slaDays: 2,
    slaTargetDate: '2026-04-02T15:00:00Z',
    cost: 290.00,
    assignedTechnician: 'Anderson Melo (Sistemas de Segurança)',
    adminNotes: 'Problema no conector balun passivo. Substituído por novo e restaurada a alimentação do canal PoE.',
    satisfactionRating: 4,
    isSlaViolated: false
  },
  {
    id: 'CHA-2026-007',
    requesterName: 'Gabriel Peixoto',
    requesterEmail: 'gabriel.peixoto@risel.com.br',
    requesterPhone: '(11) 92109-8765',
    category: 'Limpeza & Conservação',
    subitem: 'Derramamento de resíduos/óleo',
    operationalBase: 'Base Paulínia - SP',
    location: 'Galpão 1 - Armazenamento',
    description: 'Vazamento de óleo lubrificante de uma das empilhadeiras criando uma poça escorregadia no corredor principal.',
    priority: 'Crítica',
    status: 'Concluído',
    createdAt: '2026-04-18T08:15:00Z',
    updatedAt: '2026-04-18T10:30:00Z',
    slaDays: 1,
    slaTargetDate: '2026-04-18T16:15:00Z',
    cost: 150.00,
    assignedTechnician: 'Equipe de Facilities Externa (Terceirizada)',
    adminNotes: 'Aplicação de serragem absorvente, seguida por lavagem industrial com desengraxante biodegradável concentrado.',
    satisfactionRating: 5,
    feedbackText: 'Atendimento imediato. Mitigou o risco de acidentes graves no galpão.',
    isSlaViolated: false
  },
  {
    id: 'CHA-2026-008',
    requesterName: 'Helena Toledo',
    requesterEmail: 'helena.toledo@risel.com.br',
    requesterPhone: '(11) 91098-7654',
    category: 'Climatização',
    subitem: 'Ar-condicionado não resfria',
    operationalBase: 'Filial São Paulo (Matriz)',
    location: 'Bloco B - Servidores TI',
    description: 'Temperatura na sala de servidores (Datacenter) subiu para 26°C. O ar condicionado de precisão de backup não está ligando.',
    priority: 'Crítica',
    status: 'Concluído',
    createdAt: '2026-05-05T13:00:00Z',
    updatedAt: '2026-05-05T14:40:00Z',
    slaDays: 1,
    slaTargetDate: '2026-05-05T17:00:00Z',
    cost: 820.00,
    assignedTechnician: 'Marcos Vinícius (Técnico HVAC)',
    adminNotes: 'Identificado bloqueio térmico no pressostato de alta devido a sujeira na condensadora. Efetuada limpeza rápida com jato d\'água.',
    satisfactionRating: 5,
    isSlaViolated: false
  },
  {
    id: 'CHA-2026-009',
    requesterName: 'Igor Novaes',
    requesterEmail: 'igor.novaes@risel.com.br',
    requesterPhone: '(11) 90987-6543',
    category: 'Elétrica',
    subitem: 'Tomada sem energia ou com mau contato',
    operationalBase: 'Base Cubatão - SP',
    location: 'Prédio Administrativo - Copa',
    description: 'Forte cheiro de queimado vindo de uma tomada na copa perto do microondas quando em uso.',
    priority: 'Alta',
    status: 'Concluído',
    createdAt: '2026-05-20T09:15:00Z',
    updatedAt: '2026-05-20T11:00:00Z',
    slaDays: 1,
    slaTargetDate: '2026-05-20T11:15:00Z',
    cost: 120.00,
    assignedTechnician: 'Carlos Eduardo (Eletricista Sênior)',
    adminNotes: 'Bornes internos da tomada estavam frouxos, gerando centelhamento e derretimento parcial do plástico. Tomada de 20A substituída por completo.',
    satisfactionRating: 4,
    feedbackText: 'Super rápido. Trocaram a tomada antes de causar um incêndio.',
    isSlaViolated: false
  },
  {
    id: 'CHA-2026-010',
    requesterName: 'Juliana Pires',
    requesterEmail: 'juliana.pires@risel.com.br',
    requesterPhone: '(11) 99876-1122',
    category: 'Civil & Infraestrutura',
    subitem: 'Infiltração ou umidade na parede',
    operationalBase: 'Filial São Paulo (Matriz)',
    location: 'Bloco A - Área Externa',
    description: 'Infiltração grave de chuva acumulando água por trás da placa decorativa da recepção, risco de desabamento de gesso.',
    priority: 'Alta',
    status: 'Aguardando Peça',
    createdAt: '2026-06-10T14:00:00Z',
    updatedAt: '2026-06-12T10:00:00Z',
    slaDays: 5,
    slaTargetDate: '2026-06-11T14:00:00Z',
    cost: 1400.00,
    assignedTechnician: 'Roberto Silva (Marceneiro/Civil)',
    adminNotes: 'Necessário placas de gesso acartonado RU (resistente à umidade) e manta asfáltica aluminizada para calha externa. Aguardando entrega do fornecedor.',
    isSlaViolated: true
  },
  {
    id: 'CHA-2026-011',
    requesterName: 'Kleber Santos',
    requesterEmail: 'kleber.santos@risel.com.br',
    requesterPhone: '(11) 98765-2233',
    category: 'Hidráulica',
    subitem: 'Vaso sanitário entupido ou vazando',
    operationalBase: 'Base Paulínia - SP',
    location: 'Galpão 2 - Banheiro Operacional',
    description: 'Duas descargas acopladas estão vazando continuamente, desperdiçando água limpa e enchendo a fossa rapidamente.',
    priority: 'Média',
    status: 'Em Atendimento',
    createdAt: '2026-06-24T09:30:00Z',
    updatedAt: '2026-06-25T08:00:00Z',
    slaDays: 1,
    slaTargetDate: '2026-06-24T12:30:00Z',
    cost: 210.00,
    assignedTechnician: 'Julio Cezar (Encanador/Hidráulica)',
    adminNotes: 'Substituição das vedações de silicone e do mecanismo interno da boia. Uma já está consertada, trabalhando na segunda.',
    isSlaViolated: true
  },
  {
    id: 'CHA-2026-012',
    requesterName: 'Letícia Guimarães',
    requesterEmail: 'leticia.g@risel.com.br',
    requesterPhone: '(11) 97654-3344',
    category: 'Segurança',
    subitem: 'Leitor biométrico/tag sem leitura',
    operationalBase: 'Filial São Paulo (Matriz)',
    location: 'Bloco C - Portaria Interna',
    description: 'Leitor biométrico de controle de acesso não está validando as digitais dos funcionários na entrada de turnos.',
    priority: 'Alta',
    status: 'Em Análise',
    createdAt: '2026-06-25T07:15:00Z',
    updatedAt: '2026-06-25T07:30:00Z',
    slaDays: 1,
    slaTargetDate: '2026-06-25T11:15:00Z',
    cost: 0.00,
    assignedTechnician: 'Anderson Melo (Sistemas de Segurança)',
    adminNotes: 'Analisando logs de rede. Parece ser uma falha de sincronização com o servidor central de AD. Solicitando apoio à TI.',
    isSlaViolated: true
  },
  {
    id: 'CHA-2026-013',
    requesterName: 'Maurício Souza',
    requesterEmail: 'mauricio.souza@risel.com.br',
    requesterPhone: '(11) 96543-4455',
    category: 'Climatização',
    subitem: 'Vazamento de água / Gotejamento',
    operationalBase: 'Base Duque de Caxias - RJ',
    location: 'Bloco B - Desenvolvimento de TI',
    description: 'Evaporadora do ar condicionado principal da sala de descompressão está gotejando diretamente no carpete.',
    priority: 'Média',
    status: 'Novo',
    createdAt: '2026-06-25T11:45:00Z',
    updatedAt: '2026-06-25T11:45:00Z',
    slaDays: 2,
    slaTargetDate: '2026-06-25T15:45:00Z',
    cost: 0.00,
    isSlaViolated: false
  },
  {
    id: 'CHA-2026-014',
    requesterName: 'Nayara Fonseca',
    requesterEmail: 'nayara.fonseca@risel.com.br',
    requesterPhone: '(11) 95432-5566',
    category: 'Elétrica',
    subitem: 'Tomada sem energia ou com mau contato',
    operationalBase: 'Base Araucária - PR',
    location: 'Auditório Principal',
    description: 'Mesa de controle de áudio e projetor central do auditório estão completamente sem energia, impedindo evento marcado para as 15h.',
    priority: 'Crítica',
    status: 'Novo',
    createdAt: '2026-06-25T12:15:00Z',
    updatedAt: '2026-06-25T12:15:00Z',
    slaDays: 1,
    slaTargetDate: '2026-06-25T14:15:00Z',
    cost: 0.00,
    isSlaViolated: false
  },
  {
    id: 'CHA-2026-015',
    requesterName: 'Patrícia Alencar',
    requesterEmail: 'patricia.a@risel.com.br',
    requesterPhone: '(11) 94321-6677',
    category: 'Limpeza & Conservação',
    subitem: 'Necessidade de limpeza pós-obra',
    operationalBase: 'Filial São Paulo (Matriz)',
    location: 'Área Comum - Corredores Bloco A',
    description: 'Solicitação de limpeza profunda pós-obra na nova copa do departamento de compras para entrega da sala.',
    priority: 'Baixa',
    status: 'Novo',
    createdAt: '2026-06-25T12:35:00Z',
    updatedAt: '2026-06-25T12:35:00Z',
    slaDays: 5,
    slaTargetDate: '2026-06-25T20:35:00Z',
    cost: 0.00,
    isSlaViolated: false
  }
];

export const CHART_CATEGORY_DISTRIBUTION = [
  { name: 'Climatização', value: 4, cost: 2090 },
  { name: 'Elétrica', value: 3, cost: 420 },
  { name: 'Hidráulica', value: 2, cost: 530 },
  { name: 'Civil & Infra', value: 2, cost: 1980 },
  { name: 'Sistemas/Elevador', value: 1, cost: 950 },
  { name: 'Segurança', value: 2, cost: 290 },
  { name: 'Limpeza & Cons.', value: 2, cost: 150 }
];

export const CHART_MONTHLY_EVOLUTION = [
  { name: 'Jan/26', total: 8, concluidos: 8, slaNoPrazo: 8, custos: 2400 },
  { name: 'Fev/26', total: 12, concluidos: 11, slaNoPrazo: 11, custos: 3100 },
  { name: 'Mar/26', total: 15, concluidos: 14, slaNoPrazo: 13, custos: 4500 },
  { name: 'Abr/26', total: 10, concluidos: 10, slaNoPrazo: 10, custos: 2100 },
  { name: 'Mai/26', total: 14, concluidos: 14, slaNoPrazo: 14, custos: 3800 },
  { name: 'Jun/26', total: 18, concluidos: 12, slaNoPrazo: 9, custos: 5400 }
];

export const CHART_RESOLUTION_TIME_BY_PRIORITY = [
  { name: 'Crítica', tempoMedioMinutos: 45, slaMedioMinutos: 90 },
  { name: 'Alta', tempoMedioMinutos: 110, slaMedioMinutos: 210 },
  { name: 'Média', tempoMedioMinutos: 380, slaMedioMinutos: 480 },
  { name: 'Baixa', tempoMedioMinutos: 720, slaMedioMinutos: 1440 }
];

export const CHART_COST_BY_ASSET_TYPE = [
  { name: 'Compressores/Ar Cond.', planejado: 5000, realizado: 4800, preventiva: 3000 },
  { name: 'Gerador/Quadros Elét.', planejado: 3000, realizado: 3200, preventiva: 2500 },
  { name: 'Bombas/Poço Art.', planejado: 2000, realizado: 1800, preventiva: 1200 },
  { name: 'Infra/Cobertura/Portas', planejado: 4000, realizado: 4100, preventiva: 1000 },
  { name: 'Controle de Acesso/Câmeras', planejado: 1500, realizado: 1350, preventiva: 800 }
];

export const CHART_SLA_COMPLIANCE_TREND = [
  { name: 'Semana 21', conformidade: 94 },
  { name: 'Semana 22', conformidade: 95 },
  { name: 'Semana 23', conformidade: 91 },
  { name: 'Semana 24', conformidade: 96 },
  { name: 'Semana 25', conformidade: 89 }
];
